key_pool = {
    "yunwu":{
        "限时特价":{
            "model":{
                "gpt-5-2025-08-07":{
                    "prompt_cost":"1.25",
                    "completion_cost":"10",
                    "token_num":1000000
                },
            },
            "cost":0.6,
            "token":"sk-iyV6nauQXK8oF2E0x3rKRa93DLvbGpYDhGhapfUYa5QMrTfD",
        },
        "default":{
            "model":{
                "gpt-5-2025-08-07":{
                    "prompt_cost":"1.25",
                    "completion_cost":"10",
                    "token_num":1000000
                },
            },
            "cost":1,
            "token":"sk-CpQpb21q3sbL6agoCMTGeZpmR1UN33Zk6urUjADNYieIdY6h",
        },
        "逆向":{
            "model":{
                "gpt-5-2025-08-07":{
                    "prompt_cost":"1.25",
                    "completion_cost":"10",
                    "token_num":1000000
                },
            },
            "cost":1.4, 
            "token":"sk-9oJ2hJTluYeqH0k3rcoegGQOMFHfoRDLye3iL5angWGthHac",
        },
        "纯AZ":{
            "model":{
                "gpt-5-2025-08-07":{
                    "prompt_cost":"1.25",
                    "completion_cost":"10",
                    "token_num":1000000
                },
            },
            "cost":1.5,
            "token":"sk-nysXchTlcImvp7aSea67en7U4fD15r96R2yYzp8d39loNWCx",
        },
        "官转":{
            "model":{
                "gpt-5-2025-08-07":{
                    "prompt_cost":"1.25",
                    "completion_cost":"10",
                    "token_num":1000000
                },
            },
            "cost":3,
            "token":"sk-lLJkBjWaROkiGTqjsjzw5EtDiVy3aEzwrBuMOEjc745qIHD6",
        },
        "官转OpenAI":{
            "model":{
                "gpt-5-2025-08-07":{
                    "prompt_cost":"1.25",
                    "completion_cost":"10",
                    "token_num":1000000
                },
            },
            "cost":6,
            "token":"sk-GhFPrx6suIDVmgPmPM0GGsD6kV0hiA0cQUgNDz6vUICyho3m",
        },
        "优质官转OpenAI":{
            "model":{
                "gpt-5-2025-08-07":{
                    "prompt_cost":"1.25",
                    "completion_cost":"10",
                    "token_num":1000000
                },
            },
            "cost":8,
            "token":"sk-PdNao77m7aQgMFAkQglnoMNIPDOpvvDSSFPDUrELL6ZoRT30",
        }
    }
}
中转商真实倍率 = {
    "yunwu":0.5,
}
中转商urls = [
    "https://yunwu.ai",
    "https://yunwu.zeabur.app",
    "https://api.apiplus.org",
    "https://api3.wlai.vip",
    "https://api.zhongzhuan.chat",
]