
cargo fetch
cargo build
@REM cargo run --bin codex
@REM cargo install just
@REM > 定位关系                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                             
@REM   - codex-rs 是整个 codex 仓库里的一个完全独立的 Rust Cargo workspace，和上层的 codex-cli (TypeScript/Node) 等目录并列存在。                                                                                                                 
@REM   - 进入 codex-rs 后，所有子 crate 都以 codex- 前缀命名（例如 core 对应 codex-core），由根目录的 Cargo.toml 统一管理。                                                                                                                       
                                                                                                                                                                                                                                             
@REM   准备环境（Windows）                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
@REM   - 安装 Rustup（推荐使用 PowerShell 以管理员身份运行）：winget install --id Rustlang.Rustup。首次进入 codex-rs，Rustup 会自动下载 rust-toolchain.toml 指定的 toolchain（1.90.0，附带 rustfmt、clippy 等组件）。                             
@REM   - 安装 Visual Studio Build Tools 2022，勾选 “Desktop development with C++” 和 Windows 10/11 SDK；这是 Windows 上编译 Rust（MSVC toolchain）所需的 C++ 链接器。                                                                             
@REM   - 安装辅助工具（可选但常用）：                                                                                                                                                                                                             
@REM       - winget install --id GnuWin32.Grep 或直接通过 cargo install ripgrep 获得 rg。                                                                                                                                                         
@REM       - cargo install just 以使用仓库内的 justfile。                                                                                                                                                                                         
@REM       - 若需要跑 snapshot 测试：cargo install cargo-insta。                                                                                                                                                                                  
@REM   - 确保 PATH 中包含 Rustup (~\.cargo\bin) 和 Just。                                                                                                                                                                                         
                                                                                                                                                                                                                                             
@REM   常用目录操作                                                                                                                                                                                                                               
                                                                                                                                                                                                                                             
@REM   - cd C:\home\shared\dlm_blockly_all\dbit_max\dbit_core\python3.14.0\codex\codex-rs                                                                                                                                                         
@REM   - cargo fetch 或执行 just install 预下载依赖。                                                                                                                                                                                             
                                                                                                                                                                                                                                             
@REM   编译与运行                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                             
@REM   - 全量构建：cargo build（会构建 workspace 内所有 crate）。                                                                                                                                                                                 
@REM   - 仅构建 CLI 主程序：cargo build --bin codex 或 cargo build -p codex-cli（详见 cli crate）。                                                                                                                                               
@REM   - 运行 CLI：cargo run --bin codex -- <子命令>；等价简写 just codex -- <子命令>。                                                                                                                                                           
@REM   - 常用目标示例：                                                                                                                                                                                                                           
@REM       - 运行 TUI：cargo run --bin codex -- tui 或 just tui.                                                                                                                                                                                  
@REM       - 执行自动化子命令：cargo run --bin codex -- exec "指令" 或 just exec "指令"。                                                                                                                                                         
                                                                                                                                                                                                                                             
@REM   代码格式化与静态检查                                                                                                                                                                                                                       
                                                                                                                                                                                                                                             
@REM   - 格式化：just fmt（调用 cargo fmt）。                                                                                                                                                                                                     
@REM   - 按 crate 运行 Clippy 修复：just fix -p codex-core（替换为具体 crate）。                                                                                                                                                                  
@REM   - 普通 Clippy 检查：just clippy 或 cargo clippy -p codex-core.                                                                                                                                                                             
                                                                                                                                                                                                                                             
@REM   测试                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                             
@REM   - 建议使用 cargo nextest：cargo nextest run --no-fail-fast（just test 会自动调用）。                                                                                                                                                       
@REM   - 按 crate 测试：cargo test -p codex-core。                                                                                                                                                                                                
@REM   - Snapshot 相关流程参考 cargo test -p codex-tui → cargo insta pending-snapshots -p codex-tui → 审核/接受。                                                                                                                                 
                                                                                                                                                                                                                                             
@REM   其他提示                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                             
@REM   - Windows 上若使用 WSL，可直接在 WSL 中重复上述步骤（WSL 推荐使用 rustup + apt install build-essential pkg-config libssl-dev）。                                                                                                           
@REM   - 若需要交叉编译到 GNU toolchain，可 rustup target add x86_64-pc-windows-gnu 并安装对应 MinGW 工具链，但默认 MSVC 足够。                                                                                                                   
@REM   - 项目文档可参考 codex-rs/docs/*.md 以及仓库根目录 docs/。                                                                                                                                                                                 
                                                                                                                                                                                                                                             
@REM   下一步建议：                                                                                                                                                                                                                               
                                                                                                                                                                                                                                             
@REM   1. 按上述顺序安装 Rustup、Build Tools 和 Just。                                                                                                                                                                                            
@REM   2. 在 codex-rs 下执行 just install → cargo build.                                                                                                                                                                                          
@REM   3. 根据需要运行 cargo run --bin codex 或指定子命令进行验证。